apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: asia.gcr.io/poc-innovation-iot/galgal-user-producer
    newTag: 0df5a67c
  - name: asia.gcr.io/poc-innovation-iot/training-kube/galgal-user-producer
    newTag: v1.4

configMapGenerator:
  - behavior: merge
    envs:
      - configs/config.env
    name: galgal-user-producer-configmap-env
  - behavior: merge
    files:
      - configs/config.yaml
    name: galgal-user-producer-configmap-file

secretGenerator:
  - behavior: merge
    envs:
      - secrets/secret.env
    name: galgal-user-producer-secret-env

patchesStrategicMerge:
  - patches/set_resources.yaml
