apiVersion: apps/v1
kind: Deployment
metadata:
  name: galgal-user-producer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: galgal-user-producer
          resources:
            limits:
              cpu: 250m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 32Mi
