apiVersion: apps/v1
kind: Deployment
metadata:
  name: galgal-user-producer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: galgal-user-producer
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
