apiVersion: apps/v1
kind: Deployment
metadata:
  name: galgal-user-producer
  labels:
    app.kubernetes.io/name: galgal-user-producer
    app.kubernetes.io/instance: galgal-user-producer
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: galgal-user-producer
      app.kubernetes.io/instance: galgal-user-producer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: galgal-user-producer
        app.kubernetes.io/instance: galgal-user-producer
    spec:
      containers:
        - name: galgal-user-producer
          image: asia.gcr.io/poc-innovation-iot/galgal-user-producer:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: galgal-user-producer-configmap-env
            - secretRef:
                name: galgal-user-producer-secret-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 400m
              memory: 256Mi
          volumeMounts:
            - name: galgal-user-producer-configmap-file
              mountPath: /config
              readOnly: true
              # subPath: config.yaml

          # volumeMounts:
          #   - mountPath: /config
          #     name: consumer-face-cmp-result-configmap-file
          #     readOnly: true

      volumes:
        - name: galgal-user-producer-configmap-file
          configMap:
            name: galgal-user-producer-configmap-file
